### PR TITLE
projects,libraries: Renamed library folder

### PR DESCRIPTION
**Pull request by mphalke**
1. Renamed folder name from libs to libraries to be compatible with no-OS library folder. The original reasson to use 'libs' as folder name was because of file path length issue observed on command line (cmd) interface on windows-OS. As now build scripts are using 'shell' command line interface, the path length may not be a problem
2. Updated all relevant files to adapt library folder name change

### CODE REVIEW

**Comment by pamolloy** [comment]
Sorry @mphalke, it is a bit confusing.

My PR creates a new directory named `libraries` that contains submodules (following no-OS). It does not touch `lib/*.lib` and is independent of that directory. So after my PR is merged there will be the following:

```
libs
├── no-OS.lib
└── precision-converters-library.lib
libraries/
├── no-OS
└── precision-converters-library
```

**Comment by pamolloy** [comment]
Maybe it is possible to do the following:

```
libraries
├── no-OS.lib
├── precision-converters-library.lib
├── no-OS/
└── precision-converters-library/
```

I haven't tested what mbed-cli will do if it can't clone the repositories because they're already there.

**Comment by pamolloy** [comment]
It also looks like this PR includes a lot of new files

**Review by jansunil — APPROVED** [review]

**Comment by mphalke** [comment]
> Maybe it is possible to do the following (where `no-OS/` and `precision-converters-library/` are submodules):
> 
> ```
> libraries
> ├── no-OS.lib
> ├── precision-converters-library.lib
> ├── no-OS/
> └── precision-converters-library/
> ```
> 
> I haven't tested what mbed-cli will do if it can't clone the repositories because they're already there.

I was thinking the same, as it would be confusing to have 2 directories containing similar libraries. May be worth to test and see it works with Mbed web compiler as well 'make' and github CI/CD workflow.  Should work with Mbed web compiler as submodules are not handled by it. For 'make', the dependencies are required to be installed prior running 'make' target, so in this case submodules would be checked-out by user through recursive clone of repo, and those .lib files should not have any affect (my guess but need to test it out). 
I am not sure with git workflow. Is that something you want to verify?

**Comment by mphalke** [comment]
> It also looks like this PR introduces a lot of new files

Ya, I added some missing libs files required for some other projects. This should not impact existing projects though. Should have created separate commits but if required will mention same in the existing commit message.

**Comment by mphalke** [comment]
V1.0: Corrected library folder path name in clone-repos.mk file

**Comment by mphalke** [comment]
V2.0: Added license header for lv_config.h

**Review by CMinajigi — APPROVED** [review]

**Pull request merged**
